SpaceInvadersNoFrameskip-v4-apex-gpu-seed__SEED__:
    env: SpaceInvadersNoFrameskip-v4
    run: APEX
    checkpoint_freq: 10000000  # 1e7
    stop:
        episode_reward_mean: 1000
        timesteps_total: 10000000  # 10M
        # time_total_s: 72000  # 72000 s=20 hours
    config:
        seed: __SEED__ 
        framework: torch
        double_q: true
        dueling: true
        num_atoms: 1
        noisy: false
        n_step: 3
        lr: .0001
        adam_epsilon: .00015
        hiddens: [512]
        buffer_size: 1000000
        # schedule_max_timesteps: 2000000
        # exploration_final_eps: 0.01
        # exploration_fraction: .1
        prioritized_replay_alpha: 0.5
        # beta_annealing_fraction: 1.0
        final_prioritized_replay_beta: 1.0
        num_gpus: 1

        # APEX
        num_workers: 8
        num_envs_per_worker: 8
        # sample_batch_size: 20
        train_batch_size: 512
        target_network_update_freq: 50000
        timesteps_per_iteration: 25000